version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "."
    schedule:
      interval: "weekly"
    target-branch: "develop"
    assignees:
      - "LuukBlankenstijn"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

