name: ESLint
on: push

jobs:
  build:
    name: ESLint
    runs-on: [self-hosted, linux, docker]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Run
        run: npm ci && npm run lint
